[project]
name = "pygarden"
version = "0.3.24"
readme = "README.md"
description = "Package to perform everyday tasks - logging, accessing database, etc."
authors = [
    {name = "Grant, Josh", email = "grantjn@ornl.gov" },
    {name = "Jonathan Huihui", email = "huihuijk@ornl.gov"},
    {name = "Bhaskar Bishnoi", email = "bishnoib@ornl.gov"},
    {name = "Kyle Medlen", email = "medlenwk@ornl.gov"},
    {name = "Midgie MacFarland", email = "macfarlandmj@ornl.gov"},
    {name = "Chris Tester", email = "testercb@ornl.gov"},
    {name = "Jacob Isber", email = "isberj@ornl.gov"},
    {name = "Mitchell Broughton", email = "broxsonmr@ornl.gov" },
    {name = "Alec Hamaker"},
]
requires-python = ">=3.10,<3.13"
keywords = ["mixins", "logging", "database", "mysqlmixin", "postgresmixin", "pandasmixin"]
license = {file = "LICENSE"}
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
dependencies = [
    "rich>=13.7.1",
    "loguru>=0.7.2",
]

[project.optional-dependencies]
postgres = ["psycopg2-binary", 'asyncpg']
mssql = ["pymssql"]
influx = ["influxdb"]
db-pandas = [
    "pandas",
    "SQLAlchemy"
]
auth = [
    "ldap3",
    "flask"
]
scrapers = [
    "pandas",
    "urllib3",
    "selenium",
    "requests",
    "cfscrape",
    "cloudscraper",
    "beautifulsoup4",
    "websocket",
]
cli = [
    "rich",
    "click",
]
minio = [
    "minio",
]
analysis = [
    "polars",
    "polars-st",
]
all = [
    "psycopg2-binary",
    "pymssql",
    "pandas",
    "urllib3",
    "selenium",
    "requests",
    "cfscrape",
    "cloudscraper",
    "beautifulsoup4",
    "websocket",
    "influxdb",
    "ldap3",
    "flask",
    "rich",
    "click",
    "minio",
    "pandas",
    "SQLAlchemy",
    "asyncpg",
    "polars",
    "polars-st",
]
dev = [
    "ruff",
    "pytest",
    "pytest-cov",
    "moto",
    "python-hcl2",
    "bumpversion",
]
llama = [
    "llama-cpp-python>=0.2.74"
]

[project.scripts]
pygarden = "pygarden.cli:common_cli"

[project.urls]
Source = "https://code.ornl.gov/pygarden/pygarden"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
include = ["src/**/*.py", "tests/**/*.py"]
exclude = [".git", "__pycache__", "venv", "env", ".venv", ".env", "build", "dist", "docs"]

[tool.ruff.lint]
select = ["F", "E", "W", "C", "I", "D", "N"]
ignore = ["D203", "D212", "D400", "D415", "D401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.mccabe]
max-complexity = 10

[tool.bumpversion]
commit = true
tag = true
tag_name = "v{new_version}"
files = [
    "COMMON_VERSION",
    "pyproject.toml",
    "README.md",
]

[[tool.uv.index]]
url = "https://pypi.org/simple"
explicit = true
