"""PostgreSQL introspection and deterministic Trellis generation."""

# ruff: noqa: E501

from __future__ import annotations

import keyword
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pygarden.trellis.config import TableConfig, TrellisConfig
from pygarden.trellis.exceptions import TrellisGenerationError

PY_MARKER = "# Generated by pyGARDEN Trellis. DO NOT EDIT."
SQL_MARKER = "-- Generated by pyGARDEN Trellis. DO NOT EDIT."


@dataclass(frozen=True)
class Column:
    """An introspected PostgreSQL column."""

    name: str
    data_type: str
    udt_name: str
    nullable: bool
    default: str | None
    identity: bool
    generated: bool
    primary_key: bool
    ordinal: int


@dataclass(frozen=True)
class Relation:
    """An introspected table or view."""

    config: TableConfig
    columns: tuple[Column, ...]
    kind: str

    @property
    def writable(self) -> bool:
        """Return whether CRUD writes may be generated for the relation."""
        return self.kind in {"BASE TABLE", "FOREIGN", "FOREIGN TABLE"}


class PostgresIntrospector:
    """Read relation metadata from PostgreSQL catalogs."""

    def __init__(self, connection: Any):
        """Create an introspector for an asyncpg-compatible connection."""
        self.connection = connection

    async def inspect(self, table: TableConfig) -> Relation:
        """Inspect one configured table or view."""
        relation = await self.connection.fetchrow(
            """SELECT table_type FROM information_schema.tables
               WHERE table_schema=$1 AND table_name=$2
               UNION ALL SELECT 'VIEW' FROM information_schema.views
               WHERE table_schema=$1 AND table_name=$2 LIMIT 1""",
            table.schema,
            table.table,
        )
        if relation is None:
            raise TrellisGenerationError(f"Relation does not exist: {table.schema}.{table.table}")
        rows = await self.connection.fetch(
            """SELECT c.column_name, c.data_type, c.udt_name, c.is_nullable,
                      c.column_default, c.is_identity, c.is_generated, c.ordinal_position,
                      EXISTS (
                        SELECT 1 FROM information_schema.table_constraints tc
                        JOIN information_schema.key_column_usage kcu
                          ON tc.constraint_name=kcu.constraint_name
                         AND tc.constraint_schema=kcu.constraint_schema
                        WHERE tc.constraint_type='PRIMARY KEY'
                          AND tc.table_schema=c.table_schema AND tc.table_name=c.table_name
                          AND kcu.column_name=c.column_name
                      ) AS primary_key
               FROM information_schema.columns c
               WHERE c.table_schema=$1 AND c.table_name=$2 ORDER BY c.ordinal_position""",
            table.schema,
            table.table,
        )
        if not rows:
            raise TrellisGenerationError(f"No columns found for {table.schema}.{table.table}")
        columns = tuple(
            Column(
                row["column_name"],
                row["data_type"],
                row["udt_name"],
                row["is_nullable"] == "YES",
                row["column_default"],
                row["is_identity"] == "YES",
                row["is_generated"] != "NEVER",
                bool(row["primary_key"]),
                int(row["ordinal_position"]),
            )
            for row in rows
        )
        kind = relation["table_type"] if hasattr(relation, "keys") else relation[0]
        return Relation(table, columns, str(kind))


_TYPES = {
    "int2": "int",
    "int4": "int",
    "int8": "int",
    "float4": "float",
    "float8": "float",
    "numeric": "Decimal",
    "decimal": "Decimal",
    "bool": "bool",
    "text": "str",
    "varchar": "str",
    "bpchar": "str",
    "name": "str",
    "uuid": "UUID",
    "date": "date",
    "time": "time",
    "timetz": "time",
    "timestamp": "datetime",
    "timestamptz": "datetime",
    "json": "Any",
    "jsonb": "Any",
    "bytea": "bytes",
    "inet": "str",
    "cidr": "str",
}


def _field(column: Column, table: TableConfig) -> str:
    name = str(table.field_overrides.get(column.name, {}).get("name", column.name))
    name = re.sub(r"\W", "_", name)
    if not name or name[0].isdigit():
        name = f"field_{name}"
    return f"{name}_" if keyword.iskeyword(name) else name


def _type(column: Column, table: TableConfig, input_model: bool = False) -> str:
    if column.udt_name.startswith("_"):
        inferred = f"list[{_TYPES.get(column.udt_name[1:], 'Any')}]"
    else:
        inferred = _TYPES.get(column.udt_name, _TYPES.get(column.data_type, "Any"))
    result = str(table.field_overrides.get(column.name, {}).get("python_type", inferred))
    optional = column.nullable or (input_model and (column.identity or column.default is not None))
    return f"{result} | None" if optional and "None" not in result else result


def _quote(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


class TrellisGenerator:
    """Generate models, CRUD repositories, and CRUD SQL."""

    def __init__(self, config: TrellisConfig):
        """Create a generator for a validated configuration."""
        self.config = config

    def _path(self, path: Path) -> Path:
        return (self.config.base_dir / path).resolve()

    def _models_module(self) -> str:
        if self.config.generation.models_module:
            return self.config.generation.models_module
        parts = list(self.config.generation.models_output.with_suffix("").parts)
        if "src" in parts:
            parts = parts[parts.index("src") + 1 :]
        if not parts:
            raise TrellisGenerationError("Configure trellis.generate.models_module")
        return ".".join(parts)

    def _sql_ref(self, relation: Relation, name: str) -> str:
        try:
            return (
                (self._path(self.config.generation.sql_output) / relation.config.table / name)
                .relative_to(self._path(self.config.sql_path))
                .as_posix()
            )
        except ValueError as error:
            raise TrellisGenerationError("trellis.generate.sql_output must be inside trellis.sql_path") from error

    async def artifacts(self, connection: Any) -> dict[Path, str]:
        """Render all configured artifacts in memory."""
        introspector = PostgresIntrospector(connection)
        relations = [await introspector.inspect(table) for table in self.config.tables]
        result = {
            self._path(self.config.generation.models_output): self._models(relations),
            self._path(self.config.generation.repositories_output): self._repositories(relations),
        }
        root = self._path(self.config.generation.sql_output)
        for relation in relations:
            for name, contents in self._sql(relation).items():
                result[root / relation.config.table / name] = contents
        return result

    async def generate(self, connection: Any, check: bool = False) -> tuple[Path, ...]:
        """Write artifacts, or return drift without writing in check mode."""
        artifacts = await self.artifacts(connection)
        changed = tuple(p for p, text in artifacts.items() if not p.exists() or p.read_text(encoding="utf-8") != text)
        if check:
            return changed
        for path, text in artifacts.items():
            if path.exists():
                old = path.read_text(encoding="utf-8")
                marker = SQL_MARKER if path.suffix == ".sql" else PY_MARKER
                if old and not old.startswith(marker):
                    raise TrellisGenerationError(f"Refusing to overwrite non-generated file: {path}")
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
        return changed

    def _models(self, relations: list[Relation]) -> str:
        out = [
            PY_MARKER,
            '"""Schema-backed models generated by Trellis."""',
            "",
            "from datetime import date, datetime, time",
            "from decimal import Decimal",
            "from typing import Any",
            "from uuid import UUID",
            "",
            "from pygarden.trellis import map, model",
        ]
        out.extend(self.config.generation.imports)
        out.extend(("", ""))
        for relation in relations:
            out.append("@model")
            for column in relation.columns:
                out.append(
                    f'@map("{_field(column, relation.config)}", "{column.name}", primary_key={column.primary_key!r})'
                )
            out.extend(
                [
                    f"class {relation.config.model}:",
                    f'    """Generated model for {relation.config.schema}.{relation.config.table}."""',
                ]
            )
            for column in relation.columns:
                annotation = _type(column, relation.config, True)
                out.append(
                    f"    {_field(column, relation.config)}: {annotation}{' = None' if 'None' in annotation else ''}"
                )
            out.extend(("", ""))
        return "\n".join(out).rstrip() + "\n"

    def _repositories(self, relations: list[Relation]) -> str:
        names = ", ".join(r.config.model for r in relations)
        out = [
            PY_MARKER,
            '"""CRUD repositories generated by Trellis."""',
            "",
            "from pygarden.trellis import TrellisRepository, command, select",
            f"from {self._models_module()} import {names}",
            "",
            "",
        ]
        for relation in relations:
            cfg, keys = relation.config, [c for c in relation.columns if c.primary_key]
            out.extend(
                [
                    f"class {cfg.repository}(TrellisRepository):",
                    f'    """Generated CRUD access for {cfg.schema}.{cfg.table}."""',
                    "",
                    f'    @select("{self._sql_ref(relation, "select_all.sql")}", result={cfg.model}, cardinality="many")',
                    f"    async def select_all(self) -> list[{cfg.model}]:",
                    "        ...",
                ]
            )
            if keys:
                args = ", ".join(f"{_field(c, cfg)}: {_type(c, cfg)}" for c in keys)
                out.extend(
                    [
                        "",
                        f'    @select("{self._sql_ref(relation, "select_by_primary_key.sql")}", result={cfg.model}, cardinality="optional")',
                        f"    async def select_by_primary_key(self, {args}) -> {cfg.model} | None:",
                        "        ...",
                    ]
                )
            if relation.writable:
                out.extend(
                    [
                        "",
                        f'    @select("{self._sql_ref(relation, "insert.sql")}", result={cfg.model}, cardinality="one")',
                        f"    async def insert(self, model: {cfg.model}) -> {cfg.model}:",
                        "        ...",
                    ]
                )
                insertable = [c for c in relation.columns if not c.identity and not c.generated]
                required = [c for c in insertable if not c.nullable and c.default is None]
                optional = [c for c in insertable if c not in required]
                if required and optional:
                    out.extend(
                        [
                            "",
                            f'    @select("{self._sql_ref(relation, "insert_selective.sql")}", result={cfg.model}, cardinality="one")',
                            f"    async def insert_selective(self, model: {cfg.model}) -> {cfg.model}:",
                            "        ...",
                        ]
                    )
                updatable = [c for c in relation.columns if not c.primary_key and not c.generated and not c.identity]
                if keys and updatable:
                    out.extend(
                        [
                            "",
                            f'    @select("{self._sql_ref(relation, "update_by_primary_key.sql")}", result={cfg.model}, cardinality="optional")',
                            f"    async def update_by_primary_key(self, model: {cfg.model}) -> {cfg.model} | None:",
                            "        ...",
                        ]
                    )
                    out.extend(
                        [
                            "",
                            f'    @select("{self._sql_ref(relation, "update_by_primary_key_selective.sql")}", result={cfg.model}, cardinality="optional")',
                            f"    async def update_by_primary_key_selective(self, model: {cfg.model}) -> {cfg.model} | None:",
                            "        ...",
                        ]
                    )
                if keys:
                    args = ", ".join(f"{_field(c, cfg)}: {_type(c, cfg)}" for c in keys)
                    out.extend(
                        [
                            "",
                            f'    @command("{self._sql_ref(relation, "delete_by_primary_key.sql")}")',
                            f"    async def delete_by_primary_key(self, {args}) -> str | None:",
                            "        ...",
                        ]
                    )
            out.extend(("", ""))
        return "\n".join(out).rstrip() + "\n"

    def _sql(self, relation: Relation) -> dict[str, str]:
        cfg = relation.config
        table = f"{_quote(cfg.schema)}.{_quote(cfg.table)}"
        columns = ",\n       ".join(_quote(c.name) for c in relation.columns)
        prefix = f"{SQL_MARKER}\n"
        result = {"select_all.sql": f"{prefix}SELECT {columns}\nFROM {table};\n"}
        keys = [c for c in relation.columns if c.primary_key]
        if keys:
            where = " AND ".join(f"{_quote(c.name)} = :{_field(c, cfg)}" for c in keys)
            result["select_by_primary_key.sql"] = f"{prefix}SELECT {columns}\nFROM {table}\nWHERE {where};\n"
        if not relation.writable:
            return result
        insertable = [c for c in relation.columns if not c.identity and not c.generated]
        if insertable:
            names = ", ".join(_quote(c.name) for c in insertable)
            values = ", ".join(f":model.{_field(c, cfg)}" for c in insertable)
            result["insert.sql"] = f"{prefix}INSERT INTO {table} ({names})\nVALUES ({values})\nRETURNING {columns};\n"
            required = [c for c in insertable if not c.nullable and c.default is None]
            optional = [c for c in insertable if c not in required]
            if required and optional:
                selective_names = [_quote(c.name) for c in required]
                selective_values = [f":model.{_field(c, cfg)}" for c in required]
                for column in optional:
                    expression = f"model.{_field(column, cfg)} is not None"
                    selective_names.extend(
                        [f"-- trellis: if {expression}", f", {_quote(column.name)}", "-- trellis: endif"]
                    )
                    selective_values.extend(
                        [f"-- trellis: if {expression}", f", :model.{_field(column, cfg)}", "-- trellis: endif"]
                    )
                result["insert_selective.sql"] = (
                    f"{prefix}INSERT INTO {table} (\n"
                    + "\n".join(selective_names)
                    + "\n)\nVALUES (\n"
                    + "\n".join(selective_values)
                    + f"\n)\nRETURNING {columns};\n"
                )
        else:
            result["insert.sql"] = f"{prefix}INSERT INTO {table} DEFAULT VALUES\nRETURNING {columns};\n"
        updates = [c for c in relation.columns if not c.primary_key and not c.generated and not c.identity]
        if keys and updates:
            sets = ",\n    ".join(f"{_quote(c.name)} = :model.{_field(c, cfg)}" for c in updates)
            where = " AND ".join(f"{_quote(c.name)} = :model.{_field(c, cfg)}" for c in keys)
            result["update_by_primary_key.sql"] = (
                f"{prefix}UPDATE {table}\nSET {sets}\nWHERE {where}\nRETURNING {columns};\n"
            )
            seed = f"{_quote(keys[0].name)} = {_quote(keys[0].name)}"
            selective_sets = [seed]
            for column in updates:
                expression = f"model.{_field(column, cfg)} is not None"
                selective_sets.extend(
                    [
                        f"-- trellis: if {expression}",
                        f", {_quote(column.name)} = :model.{_field(column, cfg)}",
                        "-- trellis: endif",
                    ]
                )
            result["update_by_primary_key_selective.sql"] = (
                f"{prefix}UPDATE {table}\nSET " + "\n".join(selective_sets) + f"\nWHERE {where}\nRETURNING {columns};\n"
            )
        if keys:
            where = " AND ".join(f"{_quote(c.name)} = :{_field(c, cfg)}" for c in keys)
            result["delete_by_primary_key.sql"] = f"{prefix}DELETE FROM {table}\nWHERE {where};\n"
        return result
