#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Database backend for the OneID auth plugin.

Provides async Postgres access for user and session management.  All table
and column names are read from :mod:`pygarden.api.oneid.config` so they can
be customised via environment variables without touching this file.
"""

import json
import re
from uuid import UUID

from pygarden.database import Database
from pygarden.mixins.asyncpg_mixin import AsyncPostgresMixin

from . import config as c
from .session_data import SessionData

_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _quote_identifier(identifier: str) -> str:
    """Validate and quote a SQL identifier for safe interpolation."""
    if not _IDENTIFIER_RE.fullmatch(identifier):
        raise ValueError(f"Invalid SQL identifier: {identifier!r}")
    return f'"{identifier}"'


def _qualified_name(schema: str, table: str) -> str:
    """Build a safely quoted qualified table name."""
    return f"{_quote_identifier(schema)}.{_quote_identifier(table)}"


# Convenience aliases so SQL strings stay readable.
_U = _qualified_name(c.AUTH_DB_SCHEMA, c.AUTH_USERS_TABLE)
_S = _qualified_name(c.AUTH_DB_SCHEMA, c.AUTH_SESSIONS_TABLE)
_COL_USER_ID = _quote_identifier(c.COL_USER_ID)
_COL_FIRST_NAME = _quote_identifier(c.COL_FIRST_NAME)
_COL_LAST_NAME = _quote_identifier(c.COL_LAST_NAME)
_COL_EMAIL = _quote_identifier(c.COL_EMAIL)
_COL_US_CITIZEN = _quote_identifier(c.COL_US_CITIZEN)
_COL_AFFILIATION = _quote_identifier(c.COL_AFFILIATION)
_COL_APPROVED = _quote_identifier(c.COL_APPROVED)
_COL_ENABLED = _quote_identifier(c.COL_ENABLED)
_COL_ADMIN = _quote_identifier(c.COL_ADMIN)
_COL_CREATED_AT = _quote_identifier(c.COL_CREATED_AT)
_COL_UPDATED_AT = _quote_identifier(c.COL_UPDATED_AT)
_COL_SESSION_ID = _quote_identifier(c.COL_SESSION_ID)
_COL_SESSION_USER_ID = _quote_identifier(c.COL_SESSION_USER_ID)
_COL_SESSION_DATA = _quote_identifier(c.COL_SESSION_DATA)


class AuthDB(AsyncPostgresMixin, Database):
    """Async Postgres database for user and session management."""

    async def create_users_table(self) -> None:
        """Create the users table if it does not already exist."""
        query = f"""
            CREATE TABLE IF NOT EXISTS {_U} (
                {_COL_USER_ID}     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                {_COL_FIRST_NAME}  TEXT NOT NULL,
                {_COL_LAST_NAME}   TEXT NOT NULL,
                {_COL_EMAIL}       TEXT NOT NULL UNIQUE,
                {_COL_US_CITIZEN}  BOOLEAN NOT NULL DEFAULT FALSE,
                {_COL_AFFILIATION} TEXT NOT NULL DEFAULT '',
                {_COL_APPROVED}    BOOLEAN NOT NULL DEFAULT FALSE,
                {_COL_ENABLED}     BOOLEAN NOT NULL DEFAULT TRUE,
                {_COL_ADMIN}       BOOLEAN NOT NULL DEFAULT FALSE,
                {_COL_CREATED_AT}  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                {_COL_UPDATED_AT}  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                PRIMARY KEY ({_COL_USER_ID})
            );
        """
        await self.execute(query)

    async def create_sessions_table(self) -> None:
        """Create the user sessions table if it does not already exist."""
        query = f"""
            CREATE TABLE IF NOT EXISTS {_S} (
                {_COL_SESSION_ID}      CHARACTER VARYING(50) NOT NULL,
                {_COL_SESSION_USER_ID} INTEGER NOT NULL,
                {_COL_SESSION_DATA}    JSONB NOT NULL,
                {_COL_CREATED_AT}      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                {_COL_UPDATED_AT}      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                PRIMARY KEY ({_COL_SESSION_ID}),
                FOREIGN KEY ({_COL_SESSION_USER_ID})
                    REFERENCES {_U} ({_COL_USER_ID}) ON DELETE CASCADE
            );
        """
        await self.execute(query)

    async def countUsers(self) -> int:
        """
        Return the total number of registered users.

        :returns: Count of rows in the users table.
        :rtype: int
        """
        query = f"SELECT COUNT(*) FROM {_U}"
        results = await self.query(query)
        return int(results[0][0]) if results else 0

    async def getEmailStatus(self, email: str) -> str:
        """
        Return the approval/enabled status for an email address.

        :param email: Normalised user email.
        :returns: One of ``"active"``, ``"disabled"``, ``"unapproved"``, or ``"unknown"``.
        :rtype: str
        """
        query = f"""
            SELECT
                CASE
                    WHEN {_COL_APPROVED} AND {_COL_ENABLED}      THEN 'active'
                    WHEN {_COL_APPROVED} AND NOT {_COL_ENABLED}  THEN 'disabled'
                    ELSE 'unapproved'
                END AS status
            FROM {_U}
            WHERE {_COL_EMAIL} = $1
        """
        results = await self.query(query, email, as_dict=True)
        return results[0]["status"] if results and len(results) == 1 else "unknown"

    async def getUserByEmail(self, email: str) -> dict | None:
        """
        Fetch a user row by email address.

        :param email: Normalised user email.
        :returns: Row dict or ``None`` if not found.
        :rtype: dict or None
        """
        query = f"SELECT * FROM {_U} WHERE {_COL_EMAIL} = $1"
        results = await self.query(query, email, as_dict=True)
        return results[0] if results and len(results) == 1 else None

    async def createUser(
        self,
        email: str,
        first_name: str,
        last_name: str,
        us_citizen: bool = False,
        affiliation: str = "",
        *,
        approved: bool = False,
        enabled: bool = True,
        admin: bool = False,
    ) -> None:
        """
        Insert a new user row, ignoring conflicts on the email column.

        :param email: Normalised email address.
        :param first_name: Given name.
        :param last_name: Family name.
        :param us_citizen: DOE citizenship flag (optional).
        :param affiliation: DOE affiliation string (optional).
        :param approved: Whether the account starts approved.
        :param enabled: Whether the account starts enabled.
        :param admin: Whether the account starts with admin privileges.
        """
        query = f"""
            INSERT INTO {_U} (
                {_COL_EMAIL},
                {_COL_FIRST_NAME},
                {_COL_LAST_NAME},
                {_COL_US_CITIZEN},
                {_COL_AFFILIATION},
                {_COL_APPROVED},
                {_COL_ENABLED},
                {_COL_ADMIN}
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
            ON CONFLICT ({_COL_EMAIL}) DO NOTHING
        """
        await self.execute(query, email, first_name, last_name, us_citizen, affiliation, approved, enabled, admin)

    async def approveUser(self, email: str, admin: bool | None = None) -> None:
        """
        Approve a user account, optionally setting the admin flag simultaneously.

        :param email: Normalised email address.
        :param admin: If provided, also update the admin flag to this value.
        """
        if admin is None:
            query = f"""
                UPDATE {_U}
                SET {_COL_APPROVED} = TRUE, {_COL_UPDATED_AT} = NOW()
                WHERE {_COL_EMAIL} = $1
            """
            await self.execute(query, email)
            return

        query = f"""
            UPDATE {_U}
            SET {_COL_APPROVED} = TRUE, {_COL_ADMIN} = $2, {_COL_UPDATED_AT} = NOW()
            WHERE {_COL_EMAIL} = $1
        """
        await self.execute(query, email, admin)

    async def setUserAdmin(self, email: str, admin: bool) -> None:
        """
        Set the admin flag for a user and propagate the change to any open sessions.

        :param email: Normalised email address.
        :param admin: New admin flag value.
        """
        query = f"""
            WITH updated_user AS (
                UPDATE {_U}
                SET {_COL_ADMIN} = $2, {_COL_UPDATED_AT} = NOW()
                WHERE {_COL_EMAIL} = $1
                RETURNING {_COL_USER_ID}
            )
            UPDATE {_S} sessions
            SET {_COL_SESSION_DATA} = jsonb_set(
                sessions.{_COL_SESSION_DATA}::jsonb,
                '{{admin}}',
                to_jsonb($2::boolean)
            )
            FROM updated_user
            WHERE sessions.{_COL_SESSION_USER_ID} = updated_user.{_COL_USER_ID}
        """
        await self.execute(query, email, admin)

    async def listPendingUsers(self) -> list[dict]:
        """
        Return all users whose accounts are pending approval.

        :returns: List of user row dicts ordered by registration date.
        :rtype: list[dict]
        """
        query = f"""
            SELECT
                {_COL_USER_ID},
                {_COL_EMAIL},
                {_COL_FIRST_NAME},
                {_COL_LAST_NAME},
                {_COL_AFFILIATION},
                {_COL_CREATED_AT}
            FROM {_U}
            WHERE {_COL_APPROVED} = FALSE AND {_COL_ENABLED} = TRUE
            ORDER BY {_COL_CREATED_AT} ASC, {_COL_EMAIL} ASC
        """
        results = await self.query(query, as_dict=True)
        return results or []

    async def listUsers(self) -> list[dict]:
        """
        Return all users with a computed ``status`` field.

        :returns: List of user row dicts.
        :rtype: list[dict]
        """
        query = f"""
            SELECT
                {_COL_USER_ID},
                {_COL_EMAIL},
                {_COL_FIRST_NAME},
                {_COL_LAST_NAME},
                {_COL_AFFILIATION},
                {_COL_APPROVED},
                {_COL_ENABLED},
                {_COL_ADMIN},
                {_COL_CREATED_AT},
                CASE
                    WHEN {_COL_APPROVED} AND {_COL_ENABLED}     THEN 'active'
                    WHEN {_COL_APPROVED} AND NOT {_COL_ENABLED} THEN 'disabled'
                    ELSE 'unapproved'
                END AS status
            FROM {_U}
            ORDER BY {_COL_APPROVED} ASC, {_COL_ADMIN} DESC,
                     {_COL_CREATED_AT} ASC, {_COL_EMAIL} ASC
        """
        results = await self.query(query, as_dict=True)
        return results or []

    async def get_admin_emails(self) -> list[str]:
        """
        Return the email addresses of all admin users.

        :returns: List of email strings.
        :rtype: list[str]
        """
        query = f"SELECT {_COL_EMAIL} FROM {_U} WHERE {_COL_ADMIN} = TRUE"
        results = await self.query(query, as_dict=True)
        return [row[c.COL_EMAIL] for row in results] if results else []

    # ------------------------------------------------------------------
    # Session management
    # ------------------------------------------------------------------

    async def create_session(self, session_id: UUID, data: SessionData) -> None:
        """
        Persist a new session row.

        :param session_id: UUID for the session.
        :param data: :class:`~pygarden.api.oneid.session_data.SessionData` to store.
        """
        query = f"""
            INSERT INTO {_S} ({_COL_SESSION_ID}, {_COL_SESSION_USER_ID}, {_COL_SESSION_DATA})
            VALUES ($1, $2, $3)
            ON CONFLICT ({_COL_SESSION_ID}) DO NOTHING
        """
        await self.execute(query, str(session_id), data.user_id, json.dumps(data.dict()))

    async def get_session(self, session_id: UUID) -> SessionData | None:
        """
        Load a session by ID.

        :param session_id: UUID of the session to load.
        :returns: :class:`~pygarden.api.oneid.session_data.SessionData` or ``None``.
        """
        query = f"""
            SELECT {_COL_SESSION_DATA}
            FROM {_S}
            WHERE {_COL_SESSION_ID} = $1
        """
        results = await self.query(query, str(session_id), as_dict=True)
        if results and len(results) == 1:
            return SessionData(**json.loads(results[0][c.COL_SESSION_DATA]))
        return None

    async def update_session(self, session_id: UUID, data: SessionData) -> None:
        """
        Update the payload of an existing session.

        :param session_id: UUID of the session to update.
        :param data: New :class:`~pygarden.api.oneid.session_data.SessionData`.
        """
        query = f"""
            UPDATE {_S}
            SET {_COL_SESSION_DATA} = $2
            WHERE {_COL_SESSION_ID} = $1
        """
        await self.execute(query, str(session_id), json.dumps(data.dict()))

    async def delete_session(self, session_id: UUID) -> None:
        """
        Delete a session row.

        :param session_id: UUID of the session to delete.
        """
        query = f"DELETE FROM {_S} WHERE {_COL_SESSION_ID} = $1"
        await self.execute(query, str(session_id))
