import json
from uuid import UUID
from .session_data import SessionData
from mixins.asyncpg_mixin import AsyncPostgresMixin
from pygarden.database import Database

class AuthDB(AsyncPostgresMixin, Database):
    async def createUsersTable(self) -> None:
        query = """
                CREATE TABLE IF NOT EXISTS public.users (
                    user_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    first_name TEXT NOT NULL,
                    last_name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    us_citizen BOOLEAN NOT NULL,
                    affiliation TEXT NOT NULL,
                    approved BOOLEAN NOT NULL DEFAULT FALSE,
                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    admin BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    PRIMARY KEY (user_id)
                );
            """
        await self.execute(query)

    async def createUserSessionsTable(self) -> None:
        query = """
                CREATE TABLE IF NOT EXISTS public.user_sessions (
                    session_id CHARACTER VARYING(50) NOT NULL,
                    user_id INTEGER NOT NULL,
                    session_data JSONB NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    PRIMARY KEY (session_id),
                    FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON DELETE CASCADE
                );
            """
        await self.execute(query)

    async def getEmailStatus(self, email: str) -> str:
        query = """
                SELECT
                    CASE
                        WHEN approved AND enabled THEN 'active'
                        WHEN approved AND NOT enabled THEN 'disabled'
                        ELSE 'unapproved'
                    END AS status
                FROM public.users
                WHERE email = $1
            """
        results = await self.query(query, email, as_dict=True)
        return results[0]["status"] if results and len(results) == 1 else "unknown"
    
    async def getUserByEmail(self, email: str) -> dict | None:
        query = """
                SELECT *
                FROM public.users
                WHERE email = $1
            """
        results = await self.query(query, email, as_dict=True)
        return results[0] if results and len(results) == 1 else None
    
    async def createUser(
        self,
        email: str,
        first_name: str,
        last_name: str,
        us_citizen: bool,
        affiliation: str,
        *,
        approved: bool = False,
        enabled: bool = True,
        admin: bool = False,
        requested_admin: bool = False,
        password_hash: str | None = None,
        auth_provider: str = "oneid",
    ) -> None:
        query = """
                INSERT INTO public.users (
                    email,
                    first_name,
                    last_name,
                    us_citizen,
                    affiliation,
                    approved,
                    enabled,
                    admin,
                    requested_admin,
                    password_hash,
                    auth_provider
                )
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
                    ON CONFLICT (email) DO NOTHING
            """
        await self.execute(
            query,
            email,
            first_name,
            last_name,
            us_citizen,
            affiliation,
            approved,
            enabled,
            admin,
            requested_admin,
            password_hash,
            auth_provider,
        )
    
    async def approveUser(self, email: str, admin: bool | None = None) -> None:
        if admin is None:
            query = """
                    UPDATE public.users
                    SET approved = TRUE,
                        updated_at = NOW()
                    WHERE email = $1
                """
            await self.execute(query, email)
            return

        query = """
                UPDATE public.users
                SET approved = TRUE,
                    admin = $2,
                    updated_at = NOW()
                WHERE email = $1
            """
        await self.execute(query, email, admin)

    async def setUserAdmin(self, email: str, admin: bool) -> None:
        query = """
                WITH updated_user AS (
                    UPDATE public.users
                    SET admin = $2,
                        updated_at = NOW()
                    WHERE email = $1
                    RETURNING user_id
                )
                UPDATE public.user_sessions sessions
                SET session_data = jsonb_set(sessions.session_data::jsonb, '{admin}', to_jsonb($2::boolean))::text
                FROM updated_user
                WHERE sessions.user_id = updated_user.user_id
            """
        await self.execute(query, email, admin)

    async def listPendingUsers(self) -> list[dict]:
        query = """
                SELECT
                    user_id,
                    email,
                    first_name,
                    last_name,
                    affiliation,
                    requested_admin,
                    auth_provider,
                    created_at
                FROM public.users
                WHERE approved = FALSE
                  AND enabled = TRUE
                ORDER BY created_at ASC, email ASC
            """
        results = await self.query(query, as_dict=True)
        return results or []

    async def listUsers(self) -> list[dict]:
        query = """
                SELECT
                    user_id,
                    email,
                    first_name,
                    last_name,
                    affiliation,
                    approved,
                    enabled,
                    admin,
                    requested_admin,
                    auth_provider,
                    created_at,
                    CASE
                        WHEN approved AND enabled THEN 'active'
                        WHEN approved AND NOT enabled THEN 'disabled'
                        ELSE 'unapproved'
                    END AS status
                FROM public.users
                ORDER BY approved ASC, admin DESC, created_at ASC, email ASC
            """
        results = await self.query(query, as_dict=True)
        return results or []

    async def updatePasswordHash(self, email: str, password_hash: str) -> None:
        query = """
                UPDATE public.users
                SET password_hash = $2,
                    updated_at = NOW()
                WHERE email = $1
            """
        await self.execute(query, email, password_hash)

    async def upsertSimpleAdmin(
        self,
        email: str,
        first_name: str,
        last_name: str,
        affiliation: str,
        password_hash: str,
    ) -> None:
        query = """
                INSERT INTO public.users (
                    email,
                    first_name,
                    last_name,
                    us_citizen,
                    affiliation,
                    approved,
                    enabled,
                    admin,
                    requested_admin,
                    password_hash,
                    auth_provider
                )
                VALUES ($1, $2, $3, FALSE, $4, TRUE, TRUE, TRUE, FALSE, $5, 'simple')
                ON CONFLICT (email) DO UPDATE
                SET first_name = EXCLUDED.first_name,
                    last_name = EXCLUDED.last_name,
                    affiliation = EXCLUDED.affiliation,
                    approved = TRUE,
                    enabled = TRUE,
                    admin = TRUE,
                    requested_admin = FALSE,
                    password_hash = EXCLUDED.password_hash,
                    auth_provider = 'simple',
                    updated_at = NOW()
            """
        await self.execute(query, email, first_name, last_name, affiliation, password_hash)
    
    async def create_session(self, session_id: UUID, data: SessionData) -> None:
        query = """
                INSERT INTO public.user_sessions (session_id, user_id, session_data)
                    VALUES ($1, $2, $3)
                    ON CONFLICT (session_id) DO NOTHING
            """
        await self.execute(
            query,
            str(session_id),
            data.user_id,
            json.dumps(data.dict()),
        )
    
    async def get_session(self, session_id: UUID) -> SessionData | None:
        query = """
                SELECT session_data
                FROM public.user_sessions
                WHERE session_id = $1
            """
        results = await self.query(query, str(session_id), as_dict=True)
        if results and len(results) == 1:
            session_data_json = results[0]["session_data"]
            session_data_dict = json.loads(session_data_json)
            return SessionData(**session_data_dict)
        return None
    
    async def update_session(self, session_id: UUID, data: SessionData) -> None:
        query = """
                UPDATE public.user_sessions
                SET session_data = $2
                WHERE session_id = $1
            """
        await self.execute(
            query,
            str(session_id),
            json.dumps(data.dict()),
        )
    
    async def delete_session(self, session_id: UUID) -> None:
        query = """
                DELETE FROM public.user_sessions
                WHERE session_id = $1
            """
        await self.execute(query, str(session_id))
    
    async def get_admin_emails(self) -> list[str]:
        query = """
                SELECT email
                FROM public.users
                WHERE admin = TRUE
            """
        results = await self.query(query, as_dict=True)
        return [result["email"] for result in results] if results else []
